# Generated by Django 2.0.1 on 2018-01-17 12:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('news_type', models.IntegerField(choices=[(0, 'Announcement'), (1, 'News'), (2, 'Post')])),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True, default='')),
                ('new_file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete='cascade', related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
